# Generated by Django 2.0.7 on 2018-07-11 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProdFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_code', models.CharField(max_length=20)),
                ('prod_name', models.CharField(max_length=200)),
                ('prod_price', models.FloatField()),
                ('prod_gallery', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ('prod_code',),
            },
        ),
    ]
