# Generated by Django 2.0.7 on 2018-07-11 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prodfood',
            name='prod_image',
            field=models.ImageField(default='kkkk', upload_to=''),
        ),
    ]
